### ISSUE TITLE
Cryptic exception thrown by WithController in case of wrong parameters declaration

### ISSUE THREAD

**Issue by AbeniMatteo** [unosquare/embedio#351] opened 2019-08-26 11:47 UTC
**To Reproduce**
Run the following snippet:
```cs
namespace Repro
{
    using EmbedIO;
    using EmbedIO.Routing;
    using EmbedIO.WebApi;

    class Program
    {
        static void Main()
        {
            var server = new WebServer(12345);
            server.WithModule(new WebApiModule("/").WithController<MyController>());
            server.RunAsync().Wait();
        }

        private class MyController : WebApiController
        {
            [Route(HttpVerbs.Get, "/{parameter}")]
            public void Handler1(string wrongParameterName)
            {
            }

            [Route(HttpVerbs.Get, "/")]
            public void Handler2(string missingParameterName)
            {
            }
        }
    }
}
```

**Expected behavior**
`WithController` should throw an useful exception instead of:
```
System.ArgumentException: Expression of type 'System.Object' cannot be used for parameter of type 'System.String' of method 'Void Handler1(System.String)' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at EmbedIO.WebApi.WebApiModuleBase.CompileHandler(Expression factoryExpression, MethodInfo method, String route)
   at EmbedIO.WebApi.WebApiModuleBase.RegisterControllerTypeCore(Type controllerType, Expression factoryExpression)
   at EmbedIO.WebApi.WebApiModuleBase.RegisterControllerType(Type controllerType)
   at EmbedIO.WebApi.WebApiModule.RegisterController[TController]()
   at EmbedIO.WebApi.WebApiModuleExtensions.WithController[TController](WebApiModule this)
   at Program.cs:line 12
```

`Handler1` uses a wrong name  and `Handler2` uses a missing parameter.

**Version**
3.0.2

**Comment by rdeago** [comment] 2019-09-02 14:57
Hello @AbeniMatteo, thanks for pointing out this issue.

The first case (wrong parameter name) can - and will - be easily solved.

As for missing parameters, the behavior replicates what happened with previous versions of EmbedIO, i.e. the default value for the parameter is passed. Although it is probably better to throw an exception, I'd like to hear a second opinion, before I introduce a breaking change. @geoperez, any thoughts?

**Comment by AbeniMatteo** [comment] 2019-09-02 16:09
`Handler2` (missing parameter) already throws an exception, am i missing something?
The only thing i see to improve is to catch the internal `System.Linq.Expressions` exception and throw a new one with a significant message\explanation.

**Comment by rdeago** [comment] 2019-09-02 19:13
As far as I can recall, `Handler2` should pass `null` as `missingParameterName`. If it throws instead, it is a bug. Quite ironic, isn't it?

As for catching the exception and throwing a new one with a more sensible message, it is of course the way to go.

**Comment by AbeniMatteo** [comment] 2019-09-02 19:48
Just double checked, it throws:
```
System.ArgumentException: Expression of type 'System.Object' cannot be used for parameter of type 'System.String' of method 'Void Handler2(System.String)' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at EmbedIO.WebApi.WebApiModuleBase.CompileHandler(Expression factoryExpression, MethodInfo method, String route)
   at EmbedIO.WebApi.WebApiModuleBase.RegisterControllerTypeCore(Type controllerType, Expression factoryExpression)
   at EmbedIO.WebApi.WebApiModuleBase.RegisterControllerType(Type controllerType)
   at EmbedIO.WebApi.WebApiModule.RegisterController[TController]()
   at EmbedIO.WebApi.WebApiModuleExtensions.WithController[TController](WebApiModule this)
```

**Comment by geoperez** [comment] 2019-09-02 21:40
> As for missing parameters, the behavior replicates what happened with previous versions of EmbedIO, i.e. the default value for the parameter is passed. Although it is probably better to throw an exception, I'd like to hear a second opinion, before I introduce a breaking change. @geoperez, any thoughts?

This is a pending discussion that I have in my ToDo list. I was checking a route with a string optional parameter and instead of returning null, it was returning an empty string. The proper value should be null.

**Comment by rdeago** [comment] 2019-10-05 06:36
@AbeniMatteo can you confirm the issue is fixed?

**Comment by geoperez** [comment] 2019-10-06 16:46
I think I might need to release a new nuget.

**Comment by AbeniMatteo** [comment] 2019-10-09 14:19
LGTM

**Comment by geoperez** [comment] 2019-10-09 15:10
Cool, closing!

**Closed by geoperez** 2019-10-09 15:10 UTC
Labels: area:web-api, breaking-change, enhancement, v3.x
