### ISSUE TITLE
Missing `JsonDataAttribute` in 3.4.3

### ISSUE THREAD

**Issue by nd1012** [unosquare/embedio#540] opened 2022-01-31 11:01 UTC
**Describe the bug**
The `JsonDataAttribute` type is missing in the NuGET packet version 3.4.3.

**To Reproduce**
Download the version 3.4.3 from NuGET, try to use the `JsonData` attribute on a parameter or use ILSpy on the EmbedIO.dll and navigate to the `EmbedIO.WebApi` namespace.

**Expected behavior**
As I understand the `JsonDataAttribute` should be a part of the NuGET package, too!?

**Screenshots**
![image](https://user-images.githubusercontent.com/10883272/151782105-5d0ad593-1cb1-4172-8978-e7a8459e9183.png)

**Comment by rdeago** [comment] 2022-01-31 12:17
Hello @nd1012, thanks for using EmbedIO!

This issue has already been fixed by PR #468. It's just that no new version has been released since then.

As a temporary workaround, you can copy [the source code for `JsonDataAttribute`](https://github.com/unosquare/embedio/blob/v3.X/src/EmbedIO/WebApi/JsonDataAttribute.cs) into your project. It only uses public-facing API so it will compile without problems.

Closing as "not a bug" since `JsonDataAttribute` has been added _after_ the release of v3.4.3,

**Closed by rdeago** 2022-01-31 12:17 UTC
Labels: bug, v3.x, area:web-api, closed-as:not-a-bug

**Comment by nd1012** [comment] 2022-01-31 12:22
Thank you!

**Comment by GF-Huang** [comment] 2022-02-17 19:18
Same issue.
