### ISSUE TITLE
Runtime error when trying to creating WebServer - 

### ISSUE THREAD

**Issue by anantashrit** [unosquare/embedio#552] opened 2022-03-25 04:37 UTC
Hi,

I am using EmbedIO in my Xamarin application. As of now I have only one target i.e., UWP. No andriod or ios. I use following code to create a WebServer - 

```C#
var server = new WebServer(o => o
    .WithUrlPrefix(url)
    .WithMode(HttpListenerMode.EmbedIO))
    .WithLocalSessionManager()
    .WithWebApi("/api", m => m
        .WithController<XYZController>())
    .WithStaticFolder("/", HtmlRootPath, true, m => m
        .WithContentCaching(true));
```

Works fine in debug mode. But in Release mode this piece of code throws the error -

`System.Reflection.MissingRuntimeArtifactException: Cannot retrieve a MethodInfo for this delegate because the method it targeted (System.ComponentModel.TypeConverter.ConvertFromInvariantString(String)) was not enabled for metadata using the Dynamic attribute. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=616868`

I know this is not exactly EmbedIO error. But I have tried to declare many types, namespaces from the library, EmbedIO in Default.rd.xml but no success. I would really appreciate if someone can configure Default.rd.xml. 

Thanks,
Anant

**Comment by rdeago** [comment] 2022-03-26 17:26
Hello @anantashrit, thanks for using EmbedIO... or, should I say, for trying.

The cause of the exception seems to be the .NET Native compiler [stripping metadata (i.e. attributes) from all your controller methods](https://docs.microsoft.com/en-us/windows/uwp/dotnet-native/missingruntimeartifactexception-class-net-native) by default.

You can tell the compiler which attributes to retain by adding a [runtime directives file](https://docs.microsoft.com/en-us/windows/uwp/dotnet-native/runtime-directives-rd-xml-configuration-file-reference) to your application.

Having never written a Xamarin app, much less for UWP, I am unable to give you better directions, but I hope I've put you on the right track.

**Comment by rdeago** [comment] 2022-03-26 17:28
Closing this issue as this is not a problem with EmbedIO: as a matter of fact, it affects any code that uses reflection.

**Closed by rdeago** 2022-03-26 17:28 UTC
Labels: xamarin, v3.x, area:web-api, closed-as:not-a-bug
