### ISSUE TITLE
CancellationToken takes too long to cancel server task

### ISSUE THREAD

**Issue by hardywu** [unosquare/embedio#121] opened 2017-12-21 20:17 UTC
```
frontendTask.ContinueWith(result =>
	{
	    OnPropertyChanged("FrontendLabel");
	    OnPropertyChanged("ToggleFrontend");
	    frontendServer.Dispose();
	});
```
the ` frontendCancellor.Cancel();`  take a couple of minutes to complete.

**Comment by geoperez** [comment] 2017-12-21 20:42
What is frontendCancellor? Can you explain a little more?

**Comment by hardywu** [comment] 2018-01-02 06:22
Sorry for the confusion. 
```
        private void __StartFrontend(object obj)
        {
            if (!Directory.Exists(FrontendRoot))
            {
                MessageBox.Show("frontend folder is missing.");
                return;
            }
            var url = "http://localhost:8080/";
            frontendServer = new WebServer(url);
            frontendServer.RegisterModule(new StaticFilesModule(FrontendRoot));
            frontendServer.Module<StaticFilesModule>().UseRamCache = true;
            frontendServer.Module<StaticFilesModule>().DefaultExtension = ".html";
            // We don't need to add the line below. The default document is always index.html.
            //server.Module<Modules.StaticFilesWebModule>().DefaultDocument = "index.html";
            frontendCancellor = new CancellationTokenSource();
            frontendTask = frontendServer.RunAsync(frontendCancellor.Token);
            OnPropertyChanged("FrontendLabel");
            OnPropertyChanged("ToggleFrontend");
        }
        public void __StopFrontend(object obj)
        {
            frontendCancellor.Cancel();
            frontendTask.Wait();
            OnPropertyChanged("FrontendLabel");
            OnPropertyChanged("ToggleFrontend");
        }
```
Is the cancellation meant to be taking a while?

**Comment by geoperez** [comment] 2018-01-02 17:10
@hardywu what runtime are you using? .NET 46?

**Comment by hardywu** [comment] 2018-01-04 05:45
Yes.

**Comment by McFizh** [comment] 2018-04-18 14:43
I think I hit the same problem.. Trying to cancel server task takes forever, but happens immediately, if I visit the webservers address after cancel. My code looks like following:

```
System.Diagnostics.Debug.WriteLine("::1::");
serverToken.Cancel();
System.Diagnostics.Debug.WriteLine("::2::");
serverTask.Wait();
System.Diagnostics.Debug.WriteLine("::3::");
```

In console, I get the ::1:: and ::2:: lines, but ::3:: appears only after a long delay, or after visiting the servers address with browser. I think that the problem lies in this code:

https://github.com/unosquare/embedio/blob/master/src/Unosquare.Labs.EmbedIO/WebServer.cs

lines 331-333 .. 

```
var clientSocket = await Listener.GetContextAsync().ConfigureAwait(false);
if (ct.IsCancellationRequested)
  return;
```

If I understand this correctly the lister needs a new connection or timeout to continue to the cancel part of the loop. Which causes at least the issues I'm having

**Comment by geoperez** [comment] 2018-04-18 17:32
@McFizh  can you test using the branch `Issue121-CancellationDelay`?

**Comment by McFizh** [comment] 2018-04-19 19:35
This new branch fixed my issue.. Thanks :)

**Comment by geoperez** [comment] 2018-04-20 13:54
@hardywu can you verify?

**Comment by geoperez** [comment] 2018-04-20 13:55
@McFizh can you post a sample code?

**Comment by geoperez** [comment] 2018-04-20 16:02
@McFizh I was able to reproduce the issue, I committed some changes to stop the Listener.

**Comment by McFizh** [comment] 2018-04-25 18:27
With the latest changes the tcp port gets properly released and I can create/close server in a loop without problems. But with code shown below:

```
System.Diagnostics.Debug.WriteLine("!1!");
serverToken.Cancel();
System.Diagnostics.Debug.WriteLine("!2!");
serverTask.Wait();
System.Diagnostics.Debug.WriteLine("!3!");

```
I get output like this:

```
!1!
!2!
Exception thrown: 'System.ObjectDisposedException' in System.dll
!3!
```

**Comment by geoperez** [comment] 2018-04-25 18:29
Do you have the stacktrace?

**Comment by McFizh** [comment] 2018-04-25 18:41
[External Code]	
Unosquare.Labs.EmbedIO.dll!Unosquare.Net.EndPointListener.Accept(System.Net.Sockets.Socket socket, System.Net.Sockets.SocketAsyncEventArgs e, ref System.Net.Sockets.Socket accepted) Line 238
Unosquare.Labs.EmbedIO.dll!Unosquare.Net.EndPointListener.ProcessAccept(System.Net.Sockets.SocketAsyncEventArgs args) Line 270
Unosquare.Labs.EmbedIO.dll!Unosquare.Net.EndPointListener.OnAccept(object sender, System.Net.Sockets.SocketAsyncEventArgs e) Line 292
 [External Code]

**Comment by geoperez** [comment] 2018-05-08 16:35
@McFizh ??

**Closed** 2018-06-11 20:07 UTC
Labels: bug, help wanted
