### ISSUE TITLE
Static FrontEnd (Angular, React, ...): New FileSystemProvider

### ISSUE THREAD

**Issue by maarlo** [unosquare/embedio#533] opened 2021-10-08 11:58 UTC
If serving both backend and frontend in the same server and creating the frontend with a javascript framework (like React), serving only the static files in basepath is not enough when the frontend has its own routing. 

The server must serve static *index.html* file for all the unknown routes and files.

As solution, I propose modifying FileSystemProvider adding 

1. A readonly string set at constructor with the default document name (**_defaultDocumentName**)
2. Modify the constructor to set that string
3. Modify MapUrlPath return with

```c#
return !localPath.StartsWith(FileSystemPath, StringComparison.Ordinal) ? null
                : File.Exists(localPath) ? GetMappedFileInfo(mimeTypeProvider, localPath)
                : Directory.Exists(localPath) ? GetMappedDirectoryInfo(localPath)
                : GetMappedFileInfo(mimeTypeProvider, Path.Combine(FileSystemPath, _defaultDocumentName.Replace('/', Path.DirectorySeparatorChar)));
```

Instead of 

```c# 
return !localPath.StartsWith(FileSystemPath, StringComparison.Ordinal) ? null
                : File.Exists(localPath) ? GetMappedFileInfo(mimeTypeProvider, localPath)
                : Directory.Exists(localPath) ? GetMappedDirectoryInfo(localPath)
                : null;
```

To serve the files it's enough with adding 

```c#
new WebServer(webServerOptions)
  ...
  .WithModule(new FileModule("/", new FrontendSystemProvider(HtmlRootPath, [defaultDocumentName, isImmutable])).WithContentCaching(UseFileCache));
```

What do you think about?

**Comment by rdeago** [comment] 2021-10-08 12:47
Hello @maarlo, thanks for using EmbedIO!

Although I surely appreciate the effort you put in identifying the issue and providing a possible solution, I'm closing this issue for the following reasons:

1. this is a duplicate of #490
2. modifying FileSystemProvider will not solve the problem for people using other providers, e.g. ZipFileProvider, to store frontend files.

Please take a look at the solution proposed in #490 and tell us what you think.

**Closed by rdeago** 2021-10-08 12:47 UTC
Labels: duplicate, enhancement, v3.x, area:files
