### ISSUE TITLE
embedio set read lock in static files

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#47] opened 2016-10-26 08:07 UTC
Hi,

I don't know if it's a bug or a feature but since i upgrade from v1.0.17 to v1.1.0, the statics files served by embedio are read lock.

In the past version, i used to modify html, css or js file while embedio were working and just refresh browser to view result. Now, it's not possible due to some lock set by embedio. I'm forced to rexec the process and then refresh browser which is a killer workflow.

**Comment by bufferUnderrun** [comment] 2016-10-26 08:29
I don't have vs2015 to test but in StaticFilesModule.cs:243 why not using

`buffer = new FileStream(localPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);`

instead of

`buffer = new FileStream(localPath, FileMode.Open, FileAccess.Read, FileShare.Read);`

**Comment by geoperez** [comment] 2016-10-26 13:12
OK, let me take a look.

**Comment by geoperez** [comment] 2016-10-26 15:19
@bufferUnderrun new version 1.1.1 is including your suggestion. I included an unit test, and before your comment was failing. Thank you.

**Comment by bufferUnderrun** [comment] 2016-10-26 15:26
@geoperez Thank. I test as soon as nuget sync.

**Comment by bufferUnderrun** [comment] 2016-10-27 08:35
@geoperez i can edit file while embedio running like before. I will update all my projects to this version. Thanks for your quick support.

**Comment by geoperez** [comment] 2016-10-27 15:16
Closing issue.

**Comment by DavidHequet** [comment] 2017-03-13 09:49
Hi,

I have this issue too using 1.47 or 1.6 version of embedio, when server is running, i cannot save files in VS2015. Need to stop at each html/js modification.

**Comment by geoperez** [comment] 2017-03-13 17:09
Let me try to reproduce the issue again. The unit test is not failing, but it may be wrong.

**Comment by geoperez** [comment] 2017-03-13 18:25
Hello @DavidHequet , I checked with Process Monitor a file served with EmbedIO and I was able to see the issue with Visual Studio. First I check if we are creating any lock file, but it's not happening. I think the issue is only two applications trying to access a file when it's not yet available to write. Even if EmbedIO is sharing access maybe Visual Studio is not. See https://msdn.microsoft.com/en-us/library/system.io.fileshare%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

![image](https://cloud.githubusercontent.com/assets/1775792/23869135/953a5d5a-07e7-11e7-9be5-783768d5d9d9.png)

@mariodivece thoughts?

**Comment by mariodivece** [comment] 2017-04-09 01:16
This is happening to me too... Very strange issue. VS 2017, Verified the file IS NOT locked. Verifies the file can be saved with notepad++. VS Editor: A file is being used by another process (not true). After saving the file with Notepad++, I can save the file in the VS editor. Very strange issue.

**Comment by geoperez** [comment] 2017-04-10 13:53
Yeah, I think is an issue with Visual Studio. Should I close the issue?

**Comment by geoperez** [comment] 2017-05-01 18:04
Closing.

**Closed by geoperez** 2017-05-01 18:04 UTC
