### ISSUE TITLE
JSON is incorrectly surrounded by double quotes as of 3.4.1

### ISSUE THREAD

**Issue by smitha-cgi** [unosquare/embedio#557] opened 2022-05-09 09:26 UTC
**Describe the bug**
When a string is returned to a client via SendDataAsync, from version 3.4.1 onwards the string is surrounded by double quotes.

**To Reproduce**
Create a simple class object and convert it into JSON using the Newtonsoft JsonConvert.SerializeObject method. Then return that string to the client via SendDataAsync.

**Expected behavior**
Raw JSON is returned without surrounding quotes.

**Screenshots**

3.3.3
![3 3 3](https://user-images.githubusercontent.com/66452735/167380649-761b0778-bfce-432c-a07f-32a791ef4fa4.png)

3.4.1
![3 4 1](https://user-images.githubusercontent.com/66452735/167380680-55e57cb8-51b6-4581-8370-19bad5729179.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 101.0.4951.54

**Additional context**
N/A

**Comment by rdeago** [comment] 2022-05-09 11:32
Hello @smitha-cgi, thanks for using EmbedIO!

> Expected behavior
> Raw JSON is returned without surrounding quotes.

Uhm, no. `SendDataAsync` [is expected to serialize data](https://unosquare.github.io/embedio/api/EmbedIO.HttpContextExtensions.html#EmbedIO_HttpContextExtensions_SendDataAsync_EmbedIO_IHttpContext_System_Object_). You should use [`SendStringAsync`](https://unosquare.github.io/embedio/api/EmbedIO.HttpContextExtensions.html#EmbedIO_HttpContextExtensions_SendStringAsync_EmbedIO_IHttpContext_System_String_System_String_Encoding_) to send a string "as is".

I'm not sure why version 3.3.3 worked as you describe, because its source code [hansn't ever changed](https://github.com/unosquare/embedio/blame/9edabc2db5536d631b9f3c86d320ba423449b18b/src/packages/EmbedIO/HttpContextExtensions-Responses.cs#L105) since its introduction in v3.0.0.

Closing as "not a bug".

**Closed** 2022-05-09 11:32 UTC
Labels: v3.x, area:core, closed-as:not-a-bug
