### ISSUE TITLE
Xamarin iOS / tvOS: WebServer does not accept requests after app goes to background

### ISSUE THREAD

**Issue by abhishekdhotre** [unosquare/embedio#284] opened 2019-04-30 02:25 UTC
I have noticed an issue which causes my app to freeze after running my app on physical devices running iOS 11.3 and above. In my code I have used two instances of embed io web server, one to host api's on 'http://localhost:12462/' and one to host my angular website on 'http://localhost:4200'. In Xamarin application I use WebView control to display my angular website hosted at 'localhost:4200'. Everything works fine but when I lock the device and unlock it again and open the app the app doesn't respond to click events involving api calls, which I believe happens due to API server not working. The issue can be reproduced only on physical device with iOS > 11.3 (works fine with all iOS versions on the simulator). 

1. Run the application
2. Click on 'Home' button and minimize the app
3. Open the app again, everything works fine.
4. Now lock the device and unlock the device to open the app.
5. The app doesn't respond to actions involving api calls but works fine for non-api calls involving actions. (For eg: displaying pop ups)

Expected behavior
The app should respond to api calls after the device is locked then unlocked and open the app.

Device details:
 - Device: iPad Pro
 - OS: iOS 12.2

**Comment by rdeago** [comment] 2019-04-30 05:55
Hello @abhishekdhotre, thanks for using EmbedIO!

I am not a Xamarin developer, so I have to ask you for a little help in identifying the cause of the issue. Let's start with some basic information:
* which version of Xamarin iOS are you using?
* which version of EmbedIO are you using?
* which module do you use to host your APIs and how do you initialize it?
* which module do you use to host your Angular app and how do you initialize it?

From what I've gathered by googling a bit, iOS 11.3 introduced some new features related to [battery health](https://support.apple.com/en-us/HT208387). I may be wrong, but this could be related to the problem at hand.
* Is it possible that, upon unlocking, newer versions of iOS do something different (call different callbacks, raise different events, etc.) in order to wake up applications, or do not wake up some of them at all until something else happens?
* Any chance you can prevent iOS from optimizing your application on your iPad Pro and see what happens?
* Is there some way to measure your application's energy consumption, in order to understand whether it may be throttled or somewhat limited by iOS due to battery health concerns?
* Is there a way to simulate battery discharge on the simulator and see if the problem appears there too?

_(Sorry @geoperez for stealing the stage - just thought I might lend a hand by gathering some additional info)_

**Comment by abhishekdhotre** [comment] 2019-04-30 19:05
Thank for the reply @rdeago, look below for all the details related to versions I'm using:

EmbedIO version 2.5.0
Visual Studio Community 2019 for Mac
Version 8.0.4 (build 0)
Installation UUID: 112aa530-4df0-4334-93c0-3c84615b8ff8
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

Mono Framework MDK
Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

NuGet
Version: 4.8.2.5835

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.2
	2.1.8
	2.1.7
	2.1.2
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.2.104/Sdks
SDK Versions:
	2.2.104
	2.1.504
	2.1.503
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 9.2.3.0 (Visual Studio Community)
Android SDK: /Users/abhi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ac37ccd385
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

Microsoft Mobile OpenJDK
Java SDK: /Users/abhi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-04-05 16:58:56 UTC

Xamarin Designer
Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Apple Developer Tools
Xcode 10.2.1 (14490.122)
Build 10E1001

Xamarin.Mac
Version: 5.8.0.0 (Visual Studio Community)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

Xamarin.iOS
Version: 12.8.0.0 (Visual Studio Community)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

Build Information
Release ID: 800040000
Git revision: 09831ae7eef8ea58cdfad2e923c65a5bf70d27fd
Build date: 2019-04-15 23:04:13+00
Build branch: master
Xamarin extensions: 5efedb990d786142d3b54351c01ce867af7b7680

Operating System
Mac OS X 10.14.3
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Thu Dec 20 20:46:53 PST 2018
    root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

My code for initializing web servers:
To host Angular App (dist folder contains all static files related to my website): 
string location = Path.Combine(_staticFolderPath, "dist/");
   ```
private WebServer staticFilesWebServer;
var url = "http://localhost:4200";
staticFilesWebServer = new WebServer(url);
staticFilesWebServer.RegisterModule(new StaticFilesModule(location));
staticFilesWebServer.Module<StaticFilesModule>().UseRamCache = true;
staticFilesWebServer.Module<StaticFilesModule>().DefaultExtension = ".html";
staticFilesWebServer.RunAsync().ConfigureAwait(false);
```

To host my api's:
```
private WebServer applicationWebServer;
var url = "http://localhost:12462/";
applicationWebServer = new WebServer(url, RoutingStrategy.Regex);
applicationWebServer.EnableCors();
applicationWebServer.RegisterModule(new WebApiModule());
RegisterControllers(applicationWebServer);
applicationWebServer.RunAsync(ct).ConfigureAwait(false);
```
Once the staticFilesWebServer and applicationWebServer is hosted I use web view in Xamarin to display my web page using the code below:

```
private void LoadAngularApp()
{
    webView.BaseUrl = "http://localhost:4200/";
    webView.Source = "http://localhost:4200/";
    webView.ContentType = WebViewContentType.Internet;
}
```

I believe the issue is due to the web server hosting the api's. I can say that because when I redirect the WebView to some other site after unlock, say 'google.com' instead of 'localhost:4200' it works fine. Also, I noticed that the problem will be evident when my website tries to make api calls to the applicationwebserver.  I will also try to create a small sample application and share it with you. I can also check battery related checks in this application. In the meanwhile let me know if you need any other information.

**Comment by rdeago** [comment] 2019-05-01 12:40
Hi @abhishekdhotre, thanks for the info.

The code you posted looks pretty standard, I see no particular issue with it.

The version of EmbedIO you're using, however, has [a quite nasty regression in `StaticFilesModule`](https://github.com/unosquare/embedio/issues/272).

_(I can say it's nasty without offending anyone, because it was completely my fault. 😀)_

I strongly suggest you upgrade EmbedIO to latest version (2.7.2 as of today) just to be sure.

Before discovering the regression I had to debug three different clients, just to conclude that my server was misbehaving; in a similar way, it could appear that your API server is to blame, while the static files server is 404ing like mad.

If you're anything like me, every time you test for this problem you load the app, test maybe one feature, then send the device to sleep, wake it up, and test again. If this is the case, try loading three or four different pages of the app, then returning to some already-loaded page, _before_ standby. If something goes wrong, you've been bitten by issue #272!

I'm very sorry about that. The good news is it was fixed in, like, two days. Just update your EmbedIO and see Version 2.5.0 was so short lived that it doesn't even appear in the [list of releases](https://github.com/unosquare/embedio/releases)!

As for the rest of your setup, there's a more recent minor version of Xamarin you could try, but the [release notes](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/12/12.10) don't seem to say anything about sleep/wakeup, battery health etc.

Please let me know whether updating EmbedIO fixes the issue.

**Comment by mykemaas** [comment] 2019-05-09 21:36
I'm seeing the same issue.  On device only, not in the simulator.  I'm using version 2.7.2 on iPadPro iOS 12.2.  My testing confirms that the socket endpoint becomes unreachable.  No exceptions are logged.  I've tried shutting down the webserver on suspend by setting the CancellationToken, and then starting it again after resume, but still unresponsive.  I've also tried starting up a new webServer instance, but the endpoint remains down.

**Comment by mykemaas** [comment] 2019-05-15 01:37
Was able to solve by initializing the WebServer object with the HttpListenerMode.Microsoft option.  With this listener the server was able to be restarted after the iOS device awoke after being locked.  When using the HttpListenerMode.EmbedIO option, the server would close out when the application was suspended, but could never be restarted.  It appeared to be restarted, but the listener wouldn't respond to any requests.

**Comment by geoperez** [comment] 2019-05-15 01:53
Interesting. My guess is that we have something in the following line not returning the loop of the listener:

https://github.com/unosquare/embedio/blob/master/src/Unosquare.Labs.EmbedIO/System.Net/HttpListener.cs#L92

or maybe here:

https://github.com/unosquare/embedio/blob/master/src/Unosquare.Labs.EmbedIO/System.Net/EndPointListener.cs#L31

**Comment by rishabh14augshukla** [comment] 2019-12-26 08:17
@rdeago and @geoperez I am getting this issue in tvOS device when app goes to BackGround and again come in the foreground then I get the **"System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.SocketAsyncResult"** Exception .

**Comment by rdeago** [comment] 2020-03-13 16:04
I'm reopening this issue, and closing #421, to avoid the proliferation of duplicates.

# How to run EmbedIO on Apple systems (iOS, tvOS)

## 1 - Destroy and recreate your `WebServer`

Apple's [Technical Note TN2277](https://developer.apple.com/library/archive/technotes/tn2277) contains this pearl of wisdom:

  > your app should close the listening socket when it goes into the background and reopen it when it comes back into the foreground.

In other words, you MUST:

* **dispose your `WebServer`** when your app goes into the background;
* **create a new `WebServer`** when your app goes back into the foreground.

For the reasons behind the need to do so, please refer to the technical note.

There are some [known](https://stackoverflow.com/questions/5840365) [tricks](https://stackoverflow.com/questions/11032745) to keep listening sockets open even when an app is in the background. I won't go into detail on them, partly because I don't know those systems enough, partly because, as with any "trick", such methods may get your app rejected from the store.

## 2 - Use at least version 3.4.3 of EmbedIO and use `HttpListenerMode.EmbedIO`

Until version 3.4.2, there was a bug in EmbedIO that prevented a re-created `WebServer` from correctly listening. This has been fixed in [version 3.4.3](https://github.com/unosquare/embedio/releases/tag/3.4.3). Note that the fix only applies to `HttpListenerMode.EmbedIO`.

---

Please comment if, after following the above advice, your app still has the problem mentioned in this issue.

**Comment by rishabh14augshukla** [comment] 2020-03-13 18:14
@rdeago I will try with your suggestion and let you know.

**Closed** 2020-05-20 05:12 UTC
Labels: area:external, area:http, v2.x, v3.x, wontfix, xamarin

**Comment by Rades98** [comment] 2022-01-08 20:35
Hey, there is one more problem: When app goes to background and back, it throws error see my stackoverflow question: https://stackoverflow.com/questions/70614788/xamarin-ios-and-embedio-webserver-acts-strangely

**Comment by emendoza-apexmt** [comment] 2022-03-10 06:59
Hi guys, any updates or news about this concern?
Current encountering this issue in our Xamarin-iOS app 

Thanks in Advance

**Comment by SolarisYan** [comment] 2022-07-25 14:10
@emendoza-apexmt have you solve the issue?

**Comment by emendoza-apexmt** [comment] 2022-07-26 07:34
> @emendoza-apexmt have you solve the issue?

yes, some what we did, I just did what Apple suggested as option 1, where the web server will be destroyed on sleep and then re-created on resume of the App.

**Comment by emendoza-apexmt** [comment] 2022-07-28 08:49
> @emendoza-apexmt have you solve the issue?

Hi, I just did the option 1 **Destroy and recreate your WebServer**, so far it worked out fine.

**Comment by RagibNoor** [comment] 2022-10-23 15:50
> > @emendoza-apexmt have you solve the issue?
> 
> yes, some what we did, I just did what Apple suggested (option 1), where the web server will be destroyed on sleep and then re-created on resume of the App.

@emendoza-apexmt  which version of embedio you are using  ? 
and it would be helpful if you could share a sample code
